In [0]:
import numpy as np
from sklearn import datasets, metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [0]:
iris=datasets.load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,stratify=y)

iris=datasets.load_iris()

x_train= iris.data[range(1,150,2),:]
y_train=iris.target[range(1,150,2)]

x_test= iris.data[range(0,150,2),:]
y_test=iris.target[range(0,150,2)]

In [0]:
#ID3 Algorithm
clf=DecisionTreeClassifier(criterion='entropy')
clf.fit(x_train, y_train)
predictions=clf.predict(x_test)

In [0]:
print("Accuracy={0}".format(metrics.accuracy_score(predictions,y_test,normalize=True)))

print(metrics.classification_report(predictions,y_test))

print(metrics.confusion_matrix(predictions,y_test))

Accuracy=0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.84      0.95      0.89        22
           2       0.96      0.86      0.91        28

   micro avg       0.93      0.93      0.93        75
   macro avg       0.93      0.94      0.93        75
weighted avg       0.94      0.93      0.93        75

[[25  0  0]
 [ 0 21  1]
 [ 0  4 24]]


In [0]:
#CART ALgorithm
clf=DecisionTreeClassifier(criterion='gini')
clf.fit(x_train, y_train)
predictions=clf.predict(x_test)

In [0]:
print("Accuracy={0}".format(metrics.accuracy_score(predictions,y_test,normalize=True)))

print(metrics.classification_report(predictions,y_test))

print(metrics.confusion_matrix(predictions,y_test))

Accuracy=0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.84      0.95      0.89        22
           2       0.96      0.86      0.91        28

   micro avg       0.93      0.93      0.93        75
   macro avg       0.93      0.94      0.93        75
weighted avg       0.94      0.93      0.93        75

[[25  0  0]
 [ 0 21  1]
 [ 0  4 24]]


In [0]:
#C4.5 Algorithm
