In [100]:
#Importing data and understanding your data
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, metrics
from sklearn.neural_network import MLPClassifier

iris=datasets.load_iris()



In [101]:
X=iris.data
y=iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [102]:
## Preprocessing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)
StandardScaler(copy=True, with_mean=True, with_std=True)
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [105]:
mlp=MLPClassifier(hidden_layer_sizes=(60),activation='tanh',solver='adam',max_iter=1500,shuffle=False)
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
error = 

[[ 9  0  0]
 [ 0 14  1]
 [ 0  1 13]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       0.93      0.93      0.93        15
          2       0.93      0.93      0.93        14

avg / total       0.95      0.95      0.95        38

[ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
