In [0]:
import numpy as np
from sklearn import datasets, metrics
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV

In [0]:
iris=datasets.load_iris()

x_train= iris.data[range(1,150,2),:]
y_train=iris.target[range(1,150,2)]

x_test= iris.data[range(0,150,2),:]
y_test=iris.target[range(0,150,2)]

In [0]:
#LinearSVC Algorithm
clf = LinearSVC()
#NuSVC,NuSVR,SVC,SVR,LinearSVR
dict= [{'C': [ 0.001, 0.01, 0.1, 1,10,100]}]
clf=GridSearchCV(estimator=clf,param_grid=dict)
clf.fit(x_train, y_train)
predictions=clf.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the 

In [0]:
print(" Hyperplane={0}".format(clf.best_params_))
print("Accuracy={0}".format(metrics.accuracy_score(predictions,y_test,normalize=True)))

print(metrics.classification_report(predictions,y_test))

print(metrics.confusion_matrix(predictions,y_test))

 Hyperplane={'C': 1}
Accuracy=0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.88      1.00      0.94        22
           2       1.00      0.89      0.94        28

   micro avg       0.96      0.96      0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 22  0]
 [ 0  3 25]]
