In [0]:
#Matrix Multiplication

In [0]:
import numpy as np

M1=np.array([[1,0,1,0,1],[1,1,0,1,0],[1,1,1,1,0],[1,0,1,1,0],[1,1,9,2,1]])

M2=np.array([[1,2,1,4,1],[1,1,5,1,6],[1,4,1,9,0],[1,1,1,1,1],[1,1,9,2,1]])

M3=M1.dot(M2)

print(M3)

[[ 3  7 11 15  2]
 [ 3  4  7  6  8]
 [ 4  8  8 15  8]
 [ 3  7  3 14  2]
 [14 42 26 90 10]]


In [0]:
#Larger Dimensions

In [0]:
M4=np.random.rand(256,256)

M5=np.random.rand(256,512)

M6=M4.dot(M5)

print(M6)

[[64.6778774  64.94188025 62.66984525 ... 61.64731351 62.97898142
  59.96106833]
 [63.74114295 68.76721106 61.45261922 ... 62.60373185 64.12369499
  59.1563314 ]
 [62.56306733 66.83244854 59.01165752 ... 63.05142069 60.68276351
  58.00120556]
 ...
 [63.15210566 68.00132237 62.27841773 ... 63.81824747 66.01487895
  60.28701441]
 [61.00745238 64.68304332 59.691216   ... 59.62931519 63.15905522
  57.30890813]
 [65.89260796 64.88703188 58.52679937 ... 61.5378978  61.46325812
  59.36121489]]
